# -*- coding: utf-8 -*-
"""NLP_Pratical 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cNFsOgL9OK1Mu2toPHZUOAVkfN6WDx3S
"""

import nltk
from nltk import word_tokenize, pos_tag, ne_chunk
from nltk.tree import Tree

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker')
nltk.download('words')

#sample text
text="Apple Inc. was founded by Steve Jobs in Cupertion on April 1, 1976."

nltk.download('punkt_tab')
#tokenization
tokens= word_tokenize(text)

#pos tagging
nltk.download('averaged_perceptron_tagger_eng')
pos_tags=pos_tag(tokens)

nltk.download('maxent_ne_chunker_tab')
#named entity recognition
ner_tree=ne_chunk(pos_tags)

#display named entities
print("Named Entities:\n")
for subtree in ner_tree:
  if isinstance(subtree, Tree):
    entity=" ".join([word for word, tag in subtree.leaves()])
    label=subtree.label()
    print(entity, "->", label)