# -*- coding: utf-8 -*-
"""NLP_practical9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OsmTjieTvcx_DryJUOTafsic0zD0gBFt
"""

!pip install textblob

from textblob import TextBlob

#sample reviews
reviews = [
    "I Love this prodect, it is amazing!",
    "This is the worst purchase I never made."
    "The product is okay, not great."
]

#statement analysis
for review in reviews:
  blob = TextBlob(review)
  polarity = blob.sentiment.polarity
  if polarity>0:
    sentiment = "positive"
  elif polarity<0:
    sentiment = "Negative"
  else:
    sentiment = "Natural"
  print(f"Review: {review}\nSentiment:{sentiment}\nPolarity:{polarity}\n")