# -*- coding: utf-8 -*-
"""NLP_ Practical 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YUDZHfsc6QKhrVMFitzabEBfCG8N8hjv
"""

#Data type

name="NLP Lab"

hours=30

pi=3.14

topics=["Tokenization", "POS tagging", "NER"]

hours = int(input("Enter practice hours: "))

if hours > 25:
    print("Sufficient hours for learning Python")
else:
    print("Add more practice hours")

topics = ["Variables", "Loops", "Functions", "Lists"]

for topic in topics:
    print("Learning:", topic)

def greet(student_name):
    return "Welcome to " + student_name

print(greet("AL & NLP Lab"))