# -*- coding: utf-8 -*-
"""NLP_practical8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15jY5b8WHA324V-yDzb9BT7Rq4C-NYdMl
"""

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
import joblib

#sample dataset
texts=[
    "Win money now",
    "Limited offer just for you",
    "Call me later",
    "Let us have a meeting tomorrow",
    "Congratulations you won a prize",
    "Are you free today"
]

labels = ["spam","spam","ham","ham","spam","ham"]

texts=["I Love NLP","spam message","This is amazing","Win a prize now"]
labels=["Positive","Spam","Positive","Spam"]

#bag of words
vectorize=CountVectorizer()
x=vectorize.fit_transform(texts)

#train test split
x_train,x_test,y_train,y_test=train_test_split(x,labels,test_size=0.3, random_state=42)

#train classifier
model=MultinomialNB()
model.fit(x_train,y_train)

#prediction
y_pred = model.predict(x_test)

#evalution
print("Actual Label:", y_test)
print("Predicted Labels:", y_pred)
print("Accuracy:", accuracy_score(y_test,y_pred))