# -*- coding: utf-8 -*-
"""NLP_Practical 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-kNqNNbA1S6wUj2XeN_ujQres9QKyMse
"""

import nltk

from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist

nltk.download('punkt')

text="Natural language processing enables machines to understand human language."