# -*- coding: utf-8 -*-
"""NLP_Pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/125AX0tTkXnTv8d4hbhLhF6cOw0UcbxGn
"""

#import libraries
import nltk

#sample test
test="Artificial intelligence is changing the world google is located in USA"