# -*- coding: utf-8 -*-
"""NLP_practical12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1urhXEsMgEyov8f3kU222Jgsz1jjR7pch
"""

from collections import deque

graph = {
    'A':['B','C'],
    'B':['D','E'],
    'C':['F'],
    'D':[],
    'E':['F'],
    'F':[]
}

visited=[]

def bfs(start):
    visited = []
    queue = deque([start])

    while queue:
        node = queue.popleft()
        if node not in visited:
            print(node, end=" ")
            visited.append(node)
            queue.extend(graph[node])

print("BFS Traversal:")
bfs('A')

graph = {
    'A':['B','C'],
    'B':['D','E'],
    'C':['F'],
    'D':[],
    'E':['F'],
    'F':[]
}

visited=[]

def dfs(node):
    if node not in visited:
        print(node, end=" ")
        visited.append(node)
        for neighbour in graph [node]:
            dfs(neighbour)

print("DFS Traversal:")
dfs('A')