# -*- coding: utf-8 -*-
"""NLP_practical 15

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KfV1GWZkTvMxpIlfZSNbCxJcI8d6xuuU
"""

import nltk

from nltk.corpus import stopwords

from nltk.tokenize import word_tokenize, sent_tokenize

import heapq

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab') # Added to resolve LookupError

text = (
    "Artificial Intelligence (AI) is a branch of computer science that aims to create intelligent machines.\n"
    "It has applications in various fields such as healthcare, finance, education, and autonomous vehicles. Machine Learning, a subset of AI, allows systems to learn from data without explicit programming.\n"
    "AI continues to grow rapidly and impacts everyday life in multiple ways.\n"
    "Natural Language Processing enables machines to understand and interpret human language."
)

stop_words = set(stopwords.words("english"))

words = word_tokenize(text.lower())

word_frequencies = {}

for word in words:
    if word not in stop_words and word.isalpha():
        word_frequencies[word] = word_frequencies.get(word, 0) + 1

sentences = sent_tokenize(text)

sentence_scores = {}

for sent in sentences:
    for word in word_tokenize(sent.lower()):
        if word in word_frequencies:
            sentence_scores[sent] = sentence_scores.get(sent, 0) + word_frequencies[word]

# Get the top 3 sentences as summary
summary_sentences_list = heapq.nlargest(3, sentence_scores, key=sentence_scores.get)

summary = " ".join(summary_sentences_list)

print("Summary:\n", summary)