# -*- coding: utf-8 -*-
"""NLP_Practical11

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10dM_cnGd6I5fkU6uAujOL8iaxit2HRq4
"""

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import joblib

#Dataset (Hours vs mark)
x = np.array([[1],[2],[3],[4],[5],[6],[7],[8]])
y = np.array([40,45,50,60,65,70,75,85])

x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.3, random_state=1)

#train model
model = LinearRegression()
model.fit(x_train, y_train)

#prediction
y_pred = model.predict(x_test)

#evaluation
print("Actual maek:", y_test)
print("Predicted mark:", y_pred)
rmse = np.sqrt(mean_squared_error(y_test,y_pred))
print("RMSE:", rmse)

print("R2 Score:", r2_score(y_test,y_pred))