# -*- coding: utf-8 -*-
"""NLP_practical 13

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZzROQ510DXixR5rH9Dacw09wzH7BqVUh
"""

import heapq

# Example graph and heuristic for demonstration
graph = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': [],
    'E': ['F'],
    'F': []
}

heuristic = {
    'A': 10,
    'B': 7,
    'C': 5,
    'D': 3,
    'E': 2,
    'F': 0
}

def best_first_search(start, goal):
    visited = set()
    # queue stores tuples of (heuristic_value, node) to prioritize nodes
    queue = [(heuristic[start], start)]
    path = []

    while queue:
        h, node = heapq.heappop(queue)

        if node not in visited:
            path.append(node) # Add node to path when first visiting
            visited.add(node)

            if node == goal:
                return path

            # Explore neighbors
            for neighbor in graph.get(node, []): # Use .get() for safer access
                if neighbor not in visited:
                    heapq.heappush(queue, (heuristic[neighbor], neighbor))
    return None # If goal is not reachable

print("Best-First Search Path:", best_first_search('A', 'F'))

import heapq

# Heuristic values (estimated cost to goal F)
heuristic = {'A': 5, 'B': 4, 'C': 2, 'D': 3, 'E': 1, 'F': 0}

def best_first_search(start, goal):
    visited = set()
    queue = []
    heapq.heappush(queue, (heuristic[start], start))
    path = []

    while queue:
        h, node = heapq.heappop(queue)

        if node not in visited:
            path.append(node)
            visited.add(node)

            if node == goal:
                return path

            # Assuming 'graph' is defined globally or passed as an argument
            # For demonstration, I'll use a placeholder or expect it to be defined elsewhere.
            # Let's assume graph from the previous cell is available.
            graph = {
                'A': ['B', 'C'],
                'B': ['D', 'E'],
                'C': ['F'],
                'D': [],
                'E': ['F'],
                'F': []
            }
            for neighbor in graph.get(node, []):
                if neighbor not in visited:
                    heapq.heappush(queue, (heuristic[neighbor], neighbor))
    return None

print("Best-First Search Path:", best_first_search('A', 'F'))

import heapq

# Graph representation

graph = {

'A': ['B', 'C'],

'B':

['D','E'],

'C':

['F'],

'D':

[],

'E': ['F'],

'F':

[]

}

import heapq

# Define a graph with edge costs suitable for A* search
graph_for_astar = {
    'A': {'B': 1, 'C': 3},
    'B': {'D': 3, 'E': 2},
    'C': {'F': 4},
    'D': {},
    'E': {'F': 1},
    'F': {}
}

# Heuristic values (estimated cost to goal F)
heuristic_for_astar = {'A': 5, 'B': 4, 'C': 2, 'D': 3, 'E': 1, 'F': 0}

def a_star_search(start, goal):
    # open_set stores tuples of (f_cost, g_cost, node, path_list)
    open_set = [(heuristic_for_astar[start], 0, start, [start])]
    visited = set()

    while open_set:
        f, g, node, path = heapq.heappop(open_set)

        if node in visited:
            continue

        visited.add(node)

        if node == goal:
            return path, g

        for neighbor, cost in graph_for_astar[node].items():
            if neighbor not in visited:
                g_new = g + cost
                f_new = g_new + heuristic_for_astar[neighbor]
                heapq.heappush(open_set, (f_new, g_new, neighbor, path + [neighbor]))

    return None, None # If goal is not reachable

# Call the A* search function
path, cost = a_star_search('A', 'F')

print("A* Search Path:", path)
print("Total Cost:", cost)

import heapq

# Graph with edge costs

graph = {

'A': {'B': 1, 'C': 3},

'B': {'D': 3, 'E': 1},

'C': {'F': 5},

'D': {},

'E': {'F': 2},

'F': {}

}