# -*- coding: utf-8 -*-
"""NLP_practical 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ta8qoiRhb7Gvggx67bjtgoiEoQ6pzky9
"""

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
#sample corpus
corpus = [
"Natural language Processing is fun.",
"Text processing is an important NLP step." ]

#bag of words
bow = CountVectorizer()
bow_matrix = bow.fit_transform(corpus)
print("Bow Feature Names:", bow.get_feature_names_out())
print("Bow Matrix:\n", bow_matrix.toarray())

#TF-IDF
tfidf = TfidfVectorizer()
tfidf_matrix= tfidf.fit_transform(corpus)
print("TF-IDF Feature Names:", tfidf.get_feature_names_out())
print("TF-IDF Matrix:\n", tfidf_matrix.toarray())