# -*- coding: utf-8 -*-
"""NLP_practical 14

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DWEVebLeL2vCBXFW4LgirQgG64bLSTc9
"""

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Sample dataset
data = pd.DataFrame({
    'Movie': ['Movie 1','Movie 2','Movie 3','Movie 4'],
    'Description': [
        'This is a description of Movie 1',
        'This is a description of Movie 2',
        'This is a description of Movie 3',
        'This is a description of Movie 4'
    ]
})

# TF-IDF vectorization
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(data['Description'])

# Cosine similarity
cos_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

# Recommend movies similar to Movie A
movie_idx = 0
similar_movies = list(enumerate(cos_sim[movie_idx]))
similar_movies = sorted(similar_movies, key=lambda x: x[1], reverse=True)
print("Recommendations for Movies A:")
for idx, score in similar_movies[1:6]:
  print(data['Movie'][idx],"Score:",score)

