# -*- coding: utf-8 -*-
"""NLP_practical10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10MR-T9_Zra3K6JTdKA9qZLfRiM4XAs58
"""

import re
import random

patterns = {
    r'hi|hello|hey': ["Hello!", "Hi there!", "Hey! How can I help you?"],
    r'how are you': ["I am fine!", "Doing great!", "I am here to help you."],
    r'what is your name':["I am an NLP Chatbot.", "You can call me NLP bot."],
    r'bye[exit]':["goodbye!", "See you soon!", "Have a great day!"]
}

import re
import random

# Define patterns and responses
patterns = {
    r'hi|hello|hey': ["Hello!", "Hi there!", "Hey! How can I help you?"],
    r'how are you': ["I'm fine, thank you!", "Doing great! How about you?"],
    r'what is your name': ["I'm a simple chatbot.", "You can call me ChatBot."],
    r'bye|exit': ["Goodbye!", "See you later!", "Bye! Have a nice day!"]
}

def chatbot_response(user_input):
    user_input = user_input.lower()

    for pattern, responses in patterns.items():   # ✅ corrected here
        if re.search(pattern, user_input):
            return random.choice(responses)       # ✅ corrected variable

    return "Sorry, I did not understand that."    # ✅ moved outside loop


print("Chatbot is running! Type 'bye' to exit.")

while True:
    user = input("You: ")
    response = chatbot_response(user)
    print("Bot:", response)

    if re.search(r'bye|exit', user.lower()):
        break